config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }, controllers: {
    registrations: 'users/registrations'
  }

  resources :reserves
  resources :books
  resources :users

  root 'home#index'
end

app/models/reserve.rb
# frozen_string_literal: true

class Reserve < ApplicationRecord
  acts_as_paranoid

  belongs_to :book
  belongs_to :user

  enum status: { reserved: 0, returned: 1, due: 2 }

  validates :reserve_date, :devolution_date, :status, presence: true
  validate :book_is_available

  def book_is_available
    self.errors.add(:book_id, message: 'Not available') if book_is_unavailable
  end

  def book_is_unavailable
    return false if book.try(:reserves).blank?

    book.reserves.any? { |reserve|
      return false if reserve.id == self.id
      reserve.reserved? || reserve.due?
    }
  end
end

app/controllers/reserves_controller.rb
# frozen_string_literal: true

class ReservesController < ApplicationController
  load_and_authorize_resource
  before_action :set_reserve, only: %i[show edit update destroy]
  before_action :set_select_fields_options, only: %i[ new create edit update ]

  # GET /reserves or /reserves.json
  def index
    if can? :manage, Reserve
      if params[:search]
        @reserves = Reserve.joins(:book).joins(:user).where('books.title ILIKE ? OR users.name ILIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").order(devolution_date: :desc).page(params[:page])
      else
        @reserves = Reserve.order(devolution_date: :desc).page(params[:page])
      end
    else
      if params[:search]
        @reserves = current_user.reserves.joins(:book).joins(:user).where('books.title ILIKE ? OR users.name ILIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").order(devolution_date: :desc).page(params[:page])
      else
        @reserves = current_user.reserves.order(devolution_date: :desc).page(params[:page])
      end
    end
  end

  # GET /reserves/1 or /reserves/1.json
  def show; end

  # GET /reserves/new
  def new
    @reserve = Reserve.new
  end

  # GET /reserves/1/edit
  def edit; end

  # POST /reserves or /reserves.json
  def create
    @reserve = Reserve.new(reserve_params)
    @reserve.reserve_date = DateTime.now

    @reserve.book_id = reserve_params[:book_id] unless reserve_params[:book_id].present?
    @reserve.user_id = current_user.id if reserve_params[:user_id].blank? && !current_user.admin?
    @reserve.devolution_date = DateTime.now + 3.days unless reserve_params[:devolution_date].present?

    respond_to do |format|
      if @reserve.save
        if can? :manage, Reserve
          format.html { redirect_to reserve_url(@reserve), notice: 'Reserve was successfully created.' }
        else
          format.html { redirect_to books_url, status: :created, notice: 'Reserve was successfully created.'  }
        end
        format.json { render :show, status: :created, location: @reserve }
      else
        if can? :manage, Reserve
          format.html { render :new, status: :unprocessable_entity }
        else
          format.html { redirect_to books_url, status: :unprocessable_entity, alert: @reserve.errors.full_messages }
        end
        format.json { render json: @reserve.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reserves/1 or /reserves/1.json
  def update
    respond_to do |format|
      if @reserve.update(reserve_params)
        format.html { redirect_to reserve_url(@reserve), notice: 'Reserve was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserve }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reserve.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1 or /reserves/1.json
  def destroy
    @reserve.destroy

    respond_to do |format|
      format.html { redirect_to reserves_url, notice: 'Reserve was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reserve
    @reserve = Reserve.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def reserve_params
    params.require(:reserve).permit(:book_id, :user_id, :reserve_date, :devolution_date, :status)
  end

  def set_select_fields_options
    @users_array = User.clients.map { |user| [user.name, user.id] }
    @books_array = Book.available.map { |book| [book.title, book.id] }
    @books_array << [@reserve.book.title, @reserve.book_id] if @reserve.book.present?
  end
end

app/helpers/reserves_helper.rb
# frozen_string_literal: true

module ReservesHelper
end

app/views/reserves/_form.html.erb
<%= bootstrap_form_with(model: reserve) do |f| %>
  <%= render "layouts/error_messages", resource: reserve %>

  <%= f.select :user_id, @users_array, value: reserve.user_id, include_blank: "Select a user" %>
  <%= f.select :book_id, @books_array, value: reserve.book_id, include_blank: "Select a book" %>
  <%= f.date_select :devolution_date, placeholder: "Devolution date" %>
  <%= f.form_group :status, label:{ text: 'Reserve status' } do %>
    <%= f.radio_button :status, :reserved, checked: reserve.reserved? %>
    <%= f.radio_button :status, :returned, checked: reserve.returned? %>
    <%= f.radio_button :status, :due, checked: reserve.due? %>
  <% end %>
  <%= f.submit class: "btn btn-primary btn-lg w-100" %>
<% end %>

app/views/reserves/_reserve.html.erb
<div class="col">
  <div class="card h-100">
    <div class="card-body">
      <% if user_signed_in? && current_user.admin? %>
        <p class="card-text">
          <strong>User name:</strong>
          <%= reserve.user.name %>
        </p>
      <% end %>

      <p class="card-text">
        <strong>Book title:</strong>
        <%= reserve.book.title %>
      </p>

      <p class="card-text">
        <strong>Reserved at:</strong>
        <%= reserve.reserve_date.strftime("%d %B %Y") %>
      </p>

      <p class="card-text">
        <strong>Devolution:</strong>
        <%= reserve.devolution_date.strftime("%d %B %Y") %>
      </p>

      <p class="card-text">
        <strong>Status:</strong>
        <%= reserve.status %>
      </p>
    </div>

    <% if can? :manage, Book %>
      <% if btn_show %>
        <div class="card-footer">
          <%= link_to 'Show reserve', reserve_path(reserve), class: "btn btn-primary w-100" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reserves/edit.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      Editing reserve
    </h2>

    <div class="mb-4">
      <%= render "form", reserve: @reserve %>

      <div class="d-grid gap-2 col-md-8 mx-auto mt-4">
        <div class="d-flex gap-2">
          <%= link_to 'Back to reserves', reserves_path, class: "btn btn-secondary w-100" %>
        </div>

        <hr class="mb-3 mt-4" />

        <%= button_to 'Destroy this reserve', @reserve, method: :delete, class: "btn btn-danger w-100" %>
      </div>
    </div>
  </div>
</div>

app/views/reserves/index.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-10">
    <h2 class="mb-4">
      Reserves
    </h2>

    <div class="mb-2">
      <%= page_entries_info @reserves %>
    </div>

    <%= form_tag(reserves_path, method: 'get', class: "d-flex mb-3") do %>
      <%= text_field_tag(:search, params[:search], placeholder: "Search reserves", class: "form-control me-2") %>
      <%= submit_tag("Search", name: nil, class: "btn btn-success me-2") %>
      <%= link_to 'Clear', reserves_path, class: "btn btn-dark" %>
    <% end %>

    <%= render "layouts/pagination", resources: @reserves %>

    <div class="mb-4">
      <% if can? :manage, Reserve %>
        <%= link_to 'New reserve', new_reserve_path, class: "btn btn-info mb-4" %>
      <% end %>

      <div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
        <% @reserves.each do |reserve| %>
          <%= render reserve, btn_show: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reserves/new.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      New reserve
    </h2>

    <div class="mb-4">
      <%= render "form", reserve: @reserve %>
    </div>

    <%= link_to "Back to reserves", reserves_path, class: "btn btn-secondary btn-lg w-100" %>
  </div>
</div>

app/views/reserves/show.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      Show reserve
    </h2>

    <div class="mb-4">
      <%= render @reserve, btn_show: false %>

      <div class="d-grid gap-2 col-md-8 mx-auto mt-4">
        <div class="d-flex gap-2">
          <%= link_to 'Back to reserves', reserves_path, class: "btn btn-primary w-100" %>
          <%= link_to 'Edit this reserve', edit_reserve_path(@reserve), class: "btn btn-secondary w-100" %>
        </div>
      </div>
    </div>
  </div>
</div>