config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }, controllers: {
    registrations: 'users/registrations'
  }

  resources :reserves
  resources :books
  resources :users

  root 'home#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_paranoid
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  enum role: { client: 0, admin: 1 }

  has_many :reserves, dependent: :destroy
  has_many :books, through: :reserves

  scope :clients, -> { where(role: :client) }

  def user_books_categories
    return unless books.present?

    books.group(:category).count.sort_by {|_key, value| -value}
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    # GET /users/sign_up
    # def new
    #   super
    # end

    # POST /users
    # def create
    #   super
    # end

    # GET /users/edit
    # def edit
    #   super
    # end

    # PUT /users
    # def update
    #   super
    # end

    # DELETE /users
    # def destroy
    #   super
    # end

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = if params[:search]
      User.where('name ILIKE ?', "%#{params[:search]}%").order(created_at: :desc).page(params[:page])
    else
      User.order(created_at: :desc).page(params[:page])
    end
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= bootstrap_form_with(model: user) do |f| %>
  <%= render "layouts/error_messages", resource: user %>

  <%= f.text_field :name, placeholder: "Full name", autocomplete: "name" %>
  <%= f.email_field :email, placeholder: "email@example.com", autocomplete: "email" %>
  <%= f.password_field :password, placeholder: 'Password', help: '6 character minimum', autocomplete: "password" %>
  <%= f.form_group :role, label:{ text: 'User role' } do %>
    <%= f.radio_button :role, :admin, checked: user.admin? %>
    <%= f.radio_button :role, :client, checked: user.client? %>
  <% end %>
  <%= f.submit class: "btn btn-primary btn-lg w-100" %>
<% end %>

app/views/users/_user.html.erb
<div class="col">
  <div class="card h-100">
    <div class="card-body">
      <p class="card-text">
        <strong>Name:</strong>
        <%= user.name %>
      </p>

      <p class="card-text">
        <strong>Email:</strong>
        <%= user.email %>
      </p>

      <p class="card-text">
        <strong>Role:</strong>
        <%= user.role %>
      </p>
    </div>

    <% if btn_show %>
      <div class="card-footer">
        <%= link_to 'Show user', user_path(user), class: "btn btn-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      Editing user
    </h2>

    <div class="mb-4">
      <%= render "form", user: @user %>

      <div class="d-grid gap-2 col-md-8 mx-auto mt-4">
        <div class="d-flex gap-2">
          <%= link_to 'Back to users', users_path, class: "btn btn-secondary w-100" %>
        </div>

        <hr class="mb-3 mt-4" />

        <%= button_to 'Destroy this user', @user, method: :delete, class: "btn btn-danger w-100" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-10">
    <h2 class="mb-4">
      Users
    </h2>

    <div class="mb-2">
      <%= page_entries_info @users %>
    </div>

    <%= form_tag(users_path, method: 'get', class: "d-flex mb-3") do %>
      <%= text_field_tag(:search, params[:search], placeholder: "Search users", class: "form-control me-2") %>
      <%= submit_tag("Search", name: nil, class: "btn btn-success me-2") %>
      <%= link_to 'Clear', users_path, class: "btn btn-dark" %>
    <% end %>

    <%= render "layouts/pagination", resources: @users %>

    <div class="mb-4">
      <% if can? :manage, User %>
        <%= link_to 'New user', new_user_path, class: "btn btn-info mb-4" %>
      <% end %>

      <div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
        <% @users.each do |user| %>
          <%= render user, btn_show: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      New user
    </h2>

    <div class="mb-4">
      <%= render "form", user: @user %>
    </div>

    <%= link_to "Back to users", users_path, class: "btn btn-secondary btn-lg w-100" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      Show user
    </h2>

    <div class="mb-4">
      <%= render @user, btn_show: false %>

      <div class="d-grid gap-2 col-md-8 mx-auto mt-4">
        <div class="d-flex gap-2">
          <%= link_to 'Back to users', users_path, class: "btn btn-primary w-100" %>
          <%= link_to 'Edit this user', edit_user_path(@user), class: "btn btn-secondary w-100" %>
        </div>
      </div>
    </div>
  </div>
</div>