config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }, controllers: {
    registrations: 'users/registrations'
  }

  resources :reserves
  resources :books
  resources :users

  root 'home#index'
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  acts_as_paranoid

  has_many :reserves, dependent: :destroy

  validates :title, :author, :category, presence: true

  scope :available, -> { left_outer_joins(:reserves).where('reserves.id IS NULL OR reserves.status IN (1, 2)') }

  def self.available
    book_ids = Book.all.map { |book|
      book unless book.reserves.any? { |reserve| reserve.reserved? || reserve.due? }
    }.compact.pluck(:id)

    return Book.where(id: book_ids)
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  load_and_authorize_resource
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books or /books.json
  def index
    @books = Book.where('title ILIKE ?', "%#{params[:search]}%") if params[:search]

    if can? :manage, Book
      @books = @books.order(:title).page(params[:page])
    else
      @books = @books.available.order(:title).page(params[:page])
    end
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :category)
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_book.html.erb
<div class="col">
  <div class="card h-100">
    <div class="card-body">
      <p class="card-text">
        <strong>Title:</strong>
        <%= book.title %>
      </p>

      <p class="card-text">
        <strong>Author:</strong>
        <%= book.author %>
      </p>

      <p class="card-text">
        <strong>Category:</strong>
        <%= book.category %>
      </p>

      <p class="card-text">
        <strong>In library since:</strong>
        <%= book.created_at.strftime("%d %B %Y") %>
      </p>

      <% if can? :manage, Book %>
        <p class="card-text">
          <strong>Last modification:</strong>
          <%= book.updated_at.strftime("%d %B %Y") %>
        </p>
      <% end %>
    </div>

    <% if btn_show %>
      <% if can? :manage, Book %>
        <div class="card-footer">
          <%= link_to 'Show book', book_path(book), class: "btn btn-primary w-100" %>
        </div>
      <% end %>
    <% end %>

    <% if current_user && !current_user.admin? %>
      <div class="card-footer">
        <%= button_to 'Reserve book', { controller: "reserves", action: "create", reserve: { book_id: book.id }}, method: :post, class: "btn btn-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/_form.html.erb
<%= bootstrap_form_with(model: book) do |f| %>
  <%= render "layouts/error_messages", resource: book %>

  <%= f.text_field :title, placeholder: "Title of book" %>
  <%= f.text_field :author, placeholder: "Author of book" %>
  <%= f.text_field :category, placeholder: "Book category or genre" %>
  <%= f.submit class: "btn btn-primary btn-lg w-100" %>
<% end %>

app/views/books/_pagination.html.erb
<span class="pagination__desktop">
  <%= paginate books %>
</span>

<span class="pagination__mobile">
  <nav class="pagination justify-content-center" role="navigation" aria-label="pager">
    <ul class="pagination pagination-lg">
      <li class="page-item">
        <%= link_to_previous_page books, 'Previous Page', class: 'prev page-link link-secondary' %>
      </li>

      <li class="page-item">
        <%= link_to_next_page books, 'Next Page', class: 'next page-link link-secondary' %>
      </li>
    </ul>
  </nav>
</span>

app/views/books/edit.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      Editing book
    </h2>

    <div class="mb-4">
      <%= render "form", book: @book %>

      <div class="d-grid gap-2 col-md-8 mx-auto mt-4">
        <div class="d-flex gap-2">
          <%= link_to 'Back to books', books_path, class: "btn btn-secondary w-100" %>
        </div>

        <hr class="mb-3 mt-4" />

        <%= button_to 'Destroy this book', @book, method: :delete, class: "btn btn-danger w-100" %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-10">
    <h2 class="mb-4">
      Books
    </h2>

    <div class="mb-2">
      <%= page_entries_info @books %>
    </div>

    <%= form_tag(books_path, method: 'get', class: "d-flex mb-3") do %>
      <%= text_field_tag(:search, params[:search], placeholder: "Search books", class: "form-control me-2") %>
      <%= submit_tag("Search", name: nil, class: "btn btn-success me-2") %>
      <%= link_to 'Clear', books_path, class: "btn btn-dark" %>
    <% end %>

    <%= render "layouts/pagination", resources: @books %>

    <div class="mb-4">
      <% if can? :manage, Book %>
        <%= link_to 'New book', new_book_path, class: "btn btn-info mb-4" %>
      <% end %>

      <div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
        <% @books.each do |book| %>
          <%= render book, btn_show: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      New book
    </h2>

    <div class="mb-4">
      <%= render "form", book: @book %>
    </div>

    <%= link_to "Back to books", books_path, class: "btn btn-secondary btn-lg w-100" %>
  </div>
</div>

app/views/books/show.html.erb
<div class="cointainer d-flex flex-wrap align-items-center justify-content-center m-5">
  <div class="col-md-8">
    <h2>
      Show book
    </h2>

    <div class="mb-4">
      <%= render @book, btn_show: false %>

      <div class="d-grid gap-2 col-md-8 mx-auto mt-4">
        <div class="d-flex gap-2">
          <%= link_to 'Back to books', books_path, class: "btn btn-primary w-100" %>
          <%= link_to 'Edit this book', edit_book_path(@book), class: "btn btn-secondary w-100" %>
        </div>
      </div>
    </div>
  </div>
</div>